"""End-to-end: glue-opcode adjustment toggle.

Three paths exercised:

- glue off (the default): glue CSVs and the glue markdown report are not
  produced; `new_gas_all_params.csv` still carries a `glue_adjustment`
  column, uniformly zero.
- glue on: the 12 hardcoded glue opcodes are estimated and written, the
  per-test ratio table is written, and a fit whose target opcode is
  contaminated by a glue opcode (POP background in the ADD fit) ends up
  with a strictly positive `glue_adjustment` on `new_gas_all_params.csv`.
- glue on without the required driver fixtures: the pipeline refuses to
  proceed.

The priced glue-opcode set is sourced from
`evm_gasfit.glue.required.REQUIRED_GLUE_TESTS` so the tests track the
implementation without restating the set.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

from _data_synth import (
    ClientModel,
    base_config,
    make_block_limit_fixtures,
    make_glue_driver_fixtures,
    run_pipeline,
    write_standard_inputs,
)


def _main_fixtures(extra_per_million: dict[str, float] | None = None):
    return make_block_limit_fixtures(
        test_file="test_arithmetic",
        test_name="test_arithmetic",
        target_opcode="ADD",
        params={"opcode": "ADD"},
        extra_opcount_per_million=extra_per_million or {},
    )


def test_glue_disabled_skips_files(tmp_path: Path) -> None:
    fixtures = _main_fixtures(extra_per_million={"POP": 500_000})
    models = {"geth": ClientModel(intercept=80.0, slope=1.0e-5)}
    config_yaml, runtimes_csv, opcounts_json, out_dir = write_standard_inputs(
        tmp_path, fixtures=fixtures, models=models, config=base_config(), seed=1
    )
    run_pipeline(config_yaml, runtimes_csv, opcounts_json, out_dir)

    for name in (
        "glue_results.csv",
        "glue_opcodes_by_test.csv",
        "glue_opcodes_autogenerated_report.md",
    ):
        assert not (out_dir / name).exists()

    new_gas_all = pd.read_csv(out_dir / "new_gas_all_params.csv")
    assert "glue_adjustment" in new_gas_all.columns
    assert (new_gas_all["glue_adjustment"] == 0).all()


def test_glue_enabled_writes_files_and_adjusts_slope(tmp_path: Path) -> None:
    from evm_gasfit.glue.required import REQUIRED_GLUE_TESTS

    priced_glue = {op for _, op in REQUIRED_GLUE_TESTS}

    # POP background contaminates the ADD fit so the adjustment must subtract
    # the glue contribution out.
    main_fixtures = _main_fixtures(extra_per_million={"POP": 500_000})
    all_fixtures = main_fixtures + make_glue_driver_fixtures()
    models = {"geth": ClientModel(intercept=50.0, slope=2.0e-5)}
    anchor_rate = 1.0e8

    config_yaml, runtimes_csv, opcounts_json, out_dir = write_standard_inputs(
        tmp_path,
        fixtures=all_fixtures,
        models=models,
        config=base_config(glue_enabled=True, anchor_rate=anchor_rate),
        seed=3,
    )
    run_pipeline(config_yaml, runtimes_csv, opcounts_json, out_dir, glue=True)

    assert (out_dir / "glue_results.csv").exists()
    assert (out_dir / "glue_opcodes_by_test.csv").exists()
    assert (out_dir / "glue_opcodes_autogenerated_report.md").exists()

    glue_results = pd.read_csv(out_dir / "glue_results.csv")
    assert {
        "client_name",
        "glue_opcode",
        "nobs",
        "glue_runtime_ms",
        "p_value",
        "rsquared",
    }.issubset(glue_results.columns)
    # Exactly the priced opcodes appear, no more, no fewer.
    assert set(glue_results["glue_opcode"]) == priced_glue
    assert len(glue_results) == len(priced_glue)  # one client → one row per opcode

    glue_by_test = pd.read_csv(out_dir / "glue_opcodes_by_test.csv")
    assert {"test_name", "target_opcode", "glue_opcode", "corr", "ratio"}.issubset(
        glue_by_test.columns
    )

    new_gas_all = pd.read_csv(out_dir / "new_gas_all_params.csv")
    add_rows = new_gas_all[new_gas_all["gas_param"] == "OPCODE_ADD"]
    assert len(add_rows) == 1
    add_row = add_rows.iloc[0]

    # POP contaminates the ADD fit at half the target rate, so the adjustment
    # must be strictly positive (negative values are clipped to zero).
    assert float(add_row["glue_adjustment"]) > 0

    # new_gas_decimal = anchor_rate * post-adjustment runtime_ms / 1000.
    expected_decimal = anchor_rate * float(add_row["runtime_ms"]) / 1000.0
    assert float(add_row["new_gas_decimal"]) == pytest.approx(
        expected_decimal, rel=1e-9
    )


def test_glue_missing_required_test_raises(tmp_path: Path) -> None:
    """Enabling glue without the required driver fixtures must fail."""
    fixtures = _main_fixtures()  # main model only, no glue drivers
    models = {"geth": ClientModel(intercept=50.0, slope=2.0e-5)}
    config_yaml, runtimes_csv, opcounts_json, out_dir = write_standard_inputs(
        tmp_path,
        fixtures=fixtures,
        models=models,
        config=base_config(glue_enabled=True),
        noise_pct=0.0,
        seed=4,
    )

    # Acceptable for the error to surface anywhere from load up to
    # estimate_glue() — implementations may detect at different stages.
    with pytest.raises(Exception):
        run_pipeline(config_yaml, runtimes_csv, opcounts_json, out_dir, glue=True)
