"""Glue-opcode report: ``glue_opcodes_autogenerated_report.md``."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from evm_gasfit.config import Config
from evm_gasfit.modeling.results import NNLSResults

from .plots import (
    plot_glue_bootstrap,
    plot_glue_diagnostics,
    plot_glue_regression,
    slug,
)


def write_glue_report(
    out_dir: Path,
    glue_results_df: pd.DataFrame,
    glue_fits: dict[tuple[str, str], NNLSResults],
    config: Config,
) -> None:
    """Write the glue-opcode markdown report under ``out_dir``."""
    out_path = out_dir / "glue_opcodes_autogenerated_report.md"
    plots_enabled = config.output.plots

    lines: list[str] = ["# Glue opcodes report", ""]
    if glue_results_df.empty:
        out_path.write_text("\n".join(lines))
        return

    for _, row in glue_results_df.iterrows():
        client = str(row["client_name"])
        glue_opcode = str(row["glue_opcode"])
        lines.append(f"## {client} / {glue_opcode}")
        lines.append("")

        nobs = row.get("nobs")
        runtime_ms = row.get("glue_runtime_ms")
        p_value = row.get("p_value")
        rsquared = row.get("rsquared")
        lines.append(f"- nobs: {int(nobs) if not pd.isna(nobs) else 'n/a'}")
        lines.append(
            "- glue_runtime_ms: "
            + (
                "n/a"
                if isinstance(runtime_ms, float) and np.isnan(runtime_ms)
                else str(runtime_ms)
            )
        )
        lines.append(
            "- p_value: "
            + (
                "n/a"
                if isinstance(p_value, float) and np.isnan(p_value)
                else str(p_value)
            )
        )
        lines.append(
            "- rsquared: "
            + (
                "n/a"
                if isinstance(rsquared, float) and np.isnan(rsquared)
                else str(rsquared)
            )
        )
        lines.append("")

        fit = glue_fits.get((client, glue_opcode))
        if fit is not None:
            lines.append("```")
            lines.append(fit.summary())
            lines.append("```")
            lines.append("")

            if plots_enabled:
                plot_glue_regression(fit, glue_opcode=glue_opcode, client=client, out_dir=out_dir)
                plot_glue_bootstrap(fit, glue_opcode=glue_opcode, client=client, out_dir=out_dir)
                plot_glue_diagnostics(fit, glue_opcode=glue_opcode, client=client, out_dir=out_dir)
                base = slug(glue_opcode, client)
                for family in ("regression", "bootstrap", "diagnostics"):
                    lines.append(f"![](figs/glue/{base}__{family}.png)")
                    lines.append("")

    out_path.write_text("\n".join(lines))
