"""Per-spec regression report: ``runtime_estimation_autogenerated_report.md``."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from evm_gasfit.config import Config
from evm_gasfit.modeling.results import NNLSResults

from .plots import (
    plot_bootstrap,
    plot_diagnostics,
    plot_regression,
    slug,
)


def _model_by_values(row: pd.Series, model_by: list[str]) -> list[object]:
    return [row[c] for c in model_by]


def _model_by_combo(values: list[object]) -> str:
    parts = [str(v) for v in values]
    return "_".join(parts) if parts else "all"


def write_runtime_report(
    out_dir: Path,
    results_df: pd.DataFrame,
    fits: dict[tuple, NNLSResults],
    config: Config,
) -> None:
    """Write the runtime estimation markdown report under ``out_dir``."""
    out_path = out_dir / "runtime_estimation_autogenerated_report.md"
    plots_enabled = config.output.plots

    lines: list[str] = ["# Runtime estimation report", ""]
    for spec in config.resolved_models:
        spec_rows = results_df[results_df["test_name"] == spec.test_name]
        if spec_rows.empty:
            continue

        # Filter to rows that match this spec's model_by signature.
        all_mb = sorted({c for s in config.resolved_models for c in s.model_by})
        keep_idx: list[int] = []
        for idx, row in spec_rows.iterrows():
            match = True
            for col in all_mb:
                in_spec = col in spec.model_by
                val = row.get(col) if col in row.index else None
                present = not (val is None or (isinstance(val, float) and np.isnan(val)))
                if in_spec != present:
                    match = False
                    break
            if match:
                keep_idx.append(idx)
        spec_rows = spec_rows.loc[keep_idx]

        for _, row in spec_rows.iterrows():
            test_name = str(row["test_name"])
            target_opcode = str(row["target_opcode"])
            client = str(row["client_name"])
            mb_values = _model_by_values(row, spec.model_by)
            combo = _model_by_combo(mb_values)

            fit_key = (test_name, target_opcode, *mb_values, client)
            fit = fits.get(fit_key)

            heading = f"## {test_name} / {target_opcode} / {client}"
            if spec.model_by:
                heading += f" (combo: {combo})"
            lines.append(heading)
            lines.append("")

            if fit is not None:
                lines.append("```")
                lines.append(fit.summary())
                lines.append("```")
                lines.append("")

                if plots_enabled:
                    kwargs = dict(
                        target_opcode=target_opcode,
                        test_name=test_name,
                        model_by_combo=combo,
                        client=client,
                        out_dir=out_dir,
                    )
                    plot_regression(fit, **kwargs)
                    plot_bootstrap(fit, **kwargs)
                    plot_diagnostics(fit, **kwargs)
                    base = slug(target_opcode, test_name, combo, client)
                    for family in ("regression", "bootstrap", "diagnostics"):
                        lines.append(f"![](figs/runtime/{base}__{family}.png)")
                        lines.append("")

    out_path.write_text("\n".join(lines))
