"""Per-spec regression report: ``runtime_estimation_autogenerated_report.md``."""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

import numpy as np
import pandas as pd

from evm_gasfit.config import Config
from evm_gasfit.modeling.results import NNLSResults

from .plots import (
    plot_bootstrap,
    plot_diagnostics,
    plot_regression,
    slug,
)


def _anchor(text: str) -> str:
    """GitHub-flavored anchor for a heading text.

    Mirrors GFM: lowercase, drop punctuation, keep `_` and `-`, map spaces
    to `-`. Underscores in identifiers like ``test_arithmetic`` survive so
    the link points at the rendered heading id.
    """
    out: list[str] = []
    for ch in text.lower():
        if ch.isalnum() or ch in "_-":
            out.append(ch)
        elif ch == " ":
            out.append("-")
    return "".join(out)


def _fmt(value, ndigits: int = 4) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, float) and np.isnan(value):
        return "n/a"
    if isinstance(value, float):
        return f"{value:.{ndigits}g}"
    return str(value)


def _model_by_values(row: pd.Series, model_by: list[str]) -> list[object]:
    return [row[c] for c in model_by]


def _model_by_combo(values: list[object]) -> str:
    parts = [str(v) for v in values]
    return "_".join(parts) if parts else "all"


def _filter_spec_rows(
    results_df: pd.DataFrame, spec, all_model_by: list[str]
) -> pd.DataFrame:
    """Keep only rows whose model_by signature matches this spec."""
    spec_rows = results_df[results_df["test_name"] == spec.test_name]
    if spec_rows.empty:
        return spec_rows
    keep_idx: list[int] = []
    for idx, row in spec_rows.iterrows():
        match = True
        for col in all_model_by:
            in_spec = col in spec.model_by
            val = row.get(col) if col in row.index else None
            present = not (val is None or (isinstance(val, float) and np.isnan(val)))
            if in_spec != present:
                match = False
                break
        if match:
            keep_idx.append(idx)
    return spec_rows.loc[keep_idx]


def _client_headline_table(rows: list[pd.Series]) -> list[str]:
    lines = [
        "| client | nobs | R² | target_coef (ms) | p-value | 95% CI |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        nobs = row.get("nobs")
        nobs_cell = str(int(nobs)) if not pd.isna(nobs) else "n/a"
        ci_low = row.get("target_coef_conf_int_low")
        ci_high = row.get("target_coef_conf_int_high")
        ci_cell = (
            f"[{_fmt(ci_low)}, {_fmt(ci_high)}]"
            if not (pd.isna(ci_low) or pd.isna(ci_high))
            else "n/a"
        )
        lines.append(
            f"| `{row['client_name']}` | {nobs_cell} | "
            f"{_fmt(row.get('rsquared'))} | "
            f"{_fmt(row.get('target_coef_runtime_ms'))} | "
            f"{_fmt(row.get('target_coef_pvalue'))} | "
            f"{ci_cell} |"
        )
    return lines


def write_runtime_report(
    out_dir: Path,
    results_df: pd.DataFrame,
    fits: dict[tuple, NNLSResults],
    config: Config,
) -> None:
    """Write the runtime estimation markdown report under ``out_dir``."""
    out_path = out_dir / "runtime_estimation_autogenerated_report.md"
    plots_enabled = config.output.plots

    lines: list[str] = ["# Runtime estimation report", ""]
    lines.append(
        "Per-spec NNLS fits of `test_runtime_ms` against `opcount`, one row per "
        "(target opcode, test, model_by combo, client)."
    )
    lines.append("")

    # Group rows by target_opcode preserving first-appearance order across
    # specs, dedup by (test_name, target_opcode, *mb_values, client).
    all_mb = sorted({c for s in config.resolved_models for c in s.model_by})
    grouped: dict[str, list[tuple[str, list[str], list[object], pd.Series]]] = (
        defaultdict(list)
    )
    seen_keys: set[tuple] = set()
    opcode_order: list[str] = []
    for spec in config.resolved_models:
        spec_rows = _filter_spec_rows(results_df, spec, all_mb)
        if spec_rows.empty:
            continue
        for _, row in spec_rows.iterrows():
            opcode = str(row["target_opcode"])
            mb_values = _model_by_values(row, spec.model_by)
            key = (
                str(row["test_name"]),
                opcode,
                *map(str, mb_values),
                str(row["client_name"]),
            )
            if key in seen_keys:
                continue
            seen_keys.add(key)
            if opcode not in opcode_order:
                opcode_order.append(opcode)
            grouped[opcode].append(
                (str(row["test_name"]), list(spec.model_by), mb_values, row)
            )

    if not opcode_order:
        out_path.write_text("\n".join(lines))
        return

    lines.append("## Contents")
    lines.append("")
    for opcode in opcode_order:
        lines.append(f"- [{opcode}](#{_anchor(opcode)})")
    lines.append("")

    for opcode in opcode_order:
        lines.append(f"## {opcode}")
        lines.append("")

        # Sub-group within an opcode by (test_name, model_by_combo),
        # preserving first-appearance order.
        by_test: dict[tuple[str, str, tuple], list[pd.Series]] = defaultdict(list)
        per_key_mb_cols: dict[tuple[str, str, tuple], list[str]] = {}
        key_order: list[tuple[str, str, tuple]] = []
        for test_name, mb_cols, mb_values, row in grouped[opcode]:
            combo = _model_by_combo(mb_values)
            key = (test_name, combo, tuple(mb_cols))
            if key not in by_test:
                key_order.append(key)
            by_test[key].append(row)
            per_key_mb_cols[key] = mb_cols

        for key in key_order:
            test_name, combo, _mb_tuple = key
            mb_cols = per_key_mb_cols[key]
            rows = by_test[key]
            heading = f"### {test_name}"
            if mb_cols:
                heading += f" — combo `{combo}`"
            lines.append(heading)
            lines.append("")

            # Headline metrics across clients.
            rows_sorted = sorted(rows, key=lambda r: str(r["client_name"]))
            lines.extend(_client_headline_table(rows_sorted))
            lines.append("")

            for row in rows_sorted:
                client = str(row["client_name"])
                mb_values = [row[c] for c in mb_cols]
                fit_key = (test_name, opcode, *mb_values, client)
                fit = fits.get(fit_key)
                if fit is None:
                    continue

                lines.append(
                    f"<details><summary>{client} — NNLS regression summary</summary>"
                )
                lines.append("")
                lines.append("```")
                lines.append(fit.summary())
                lines.append("```")
                lines.append("")

                if plots_enabled:
                    kwargs = dict(
                        target_opcode=opcode,
                        test_name=test_name,
                        model_by_combo=combo,
                        client=client,
                        out_dir=out_dir,
                    )
                    plot_regression(fit, **kwargs)
                    plot_bootstrap(fit, **kwargs)
                    plot_diagnostics(fit, **kwargs)
                    base = slug(opcode, test_name, combo, client)
                    for family in ("regression", "bootstrap", "diagnostics"):
                        lines.append(f"![](figs/runtime/{base}__{family}.png)")
                        lines.append("")

                lines.append("</details>")
                lines.append("")

    out_path.write_text("\n".join(lines))
